spring:
  redis:
    host: 192.168.150.130
    password: L1tTlE+++
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        time-between-eviction-runs: 10s
  data:
    mongodb:
      username: douyin
      password: "123456"
      host: 192.168.150.130
      port: 27017
      database: Crapsc
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.130:8848
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2373506982@qq.com
    password: tyfadnzuwdbrdjed
    port: 587
    properties:
      debug: true


  application:
    name: userServer

server:
  port: 9001